server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: server-zuul

#动态路由 服务过滤
zuul:
  routes:
    server-first:
      path: /server-first/**
      serviceId: server-ribbon
    server-second:
      path: /server-second/**
      serviceId: server-feign