server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #表示当前服务是否注册到eureka上，默认为true。由于当前应用就是eureka server，所以置为false，表示不向注册中心注册自己
    register-with-eureka: false
    #表示是否从eureka获取注册服务信息，默认为true。单节点eureka不需要同步其他eureka的节点数据
    #默认为true，表示检索服务，获取eureka服务清单
    fetch-registry: false
    #设置其他服务注册到Eureka的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭自我保护模式
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
