server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/ZzzLJ/SpringCloud-Learning
          #配置仓库路径
          search-paths: respo
          #访问git仓库的用户名，公开仓库可以不填写用户名和用户密码
          username:
          #访问git仓库的用户密码
          password:
      #配置仓库的分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/